# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCTGNPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCTGNPlayer
  pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
  pod 'FileBrowser', :git => 'https://github.com/Algonrey/FileBrowser.git'
  pod 'ZIPFoundation', '~> 0.9'
end
