//
//  CardSet.swift
//  RingLord
//
//  Created by Greg Langmead on 12/22/20.
//

import Foundation

public struct Cycle {} // ordered list of packs
public struct Quest {} // list of quest cards and list of encounter cards (also heroes?) with duplication. Future: "Staging Setup" and other octgn details

public struct CardSet: Identifiable, CustomStringConvertible, CustomPlaygroundDisplayConvertible {
    public var name: String
    public var id: String
    public var cards: [MemoryCard]
    public var releaseDate: Date?
    public var description: String { return "Set '\(name)', \(cards.count) cards\n  \(cards)" }
    public var playgroundDescription: Any { return description }
}

public struct Pack: Identifiable, CustomStringConvertible, CustomPlaygroundDisplayConvertible {
    public let name: String
    public let code: String
    public let position: Int
    public let cyclePosition: Int
    public let ringdDBId: Int
    public var id: Int { return ringdDBId }
    public var description: String {
        return "Pack \(name)"
    }
    public var playgroundDescription: Any { return description }
}

extension CardSet {
public static func coreSet() -> CardSet {
    return CardSet(name: "Core Set", id: "51223bd0-ffd1-11df-a976-0801200c9000", cards: [
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9001", name: "Aragorn", number: Optional(1), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Leadership"), traits: Optional("Dunedain. Noble. Ranger."), keywords: Optional("Sentinel."), cost: Optional("12"), willpower: Optional("2"), attack: Optional("3"), defense: Optional("2"), health: Optional("5"), text: Optional("Response: After Aragorn commits to a quest, spend 1 resource from his resource pool to ready him.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9002", name: "Théodred", number: Optional(2), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Leadership"), traits: Optional("Noble. Rohan. Warrior."), keywords: nil, cost: Optional("8"), willpower: Optional("1"), attack: Optional("2"), defense: Optional("1"), health: Optional("4"), text: Optional("Response: After Theodred commits to a quest, choose a hero committed to that quest. Add 1 resource to that hero\'s resource pool.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9003", name: "Glóin", number: Optional(3), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Leadership"), traits: Optional("Dwarf. Noble."), keywords: nil, cost: Optional("9"), willpower: Optional("2"), attack: Optional("2"), defense: Optional("1"), health: Optional("4"), text: Optional("Response: After Gloin suffers damage, add 1 resource to his resource pool for each point of damage he just suffered.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9004", name: "Gimli", number: Optional(4), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Tactics"), traits: Optional("Dwarf. Noble. Warrior."), keywords: nil, cost: Optional("11"), willpower: Optional("2"), attack: Optional("2"), defense: Optional("2"), health: Optional("5"), text: Optional("Gimli gets +1 Û for each damage token on him.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9005", name: "Legolas", number: Optional(5), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Tactics"), traits: Optional("Noble. Silvan. Warrior."), keywords: Optional("Ranged."), cost: Optional("9"), willpower: Optional("1"), attack: Optional("3"), defense: Optional("1"), health: Optional("4"), text: Optional("Response: After Legolas participates in an attack that destroys an enemy, place 2 progress tokens on the current quest.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9006", name: "Thalin", number: Optional(6), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Tactics"), traits: Optional("Dwarf. Warrior."), keywords: nil, cost: Optional("9"), willpower: Optional("1"), attack: Optional("2"), defense: Optional("2"), health: Optional("4"), text: Optional("While Thalin is committed to a quest, deal 1 damage to each enemy as it is revealed by the encounter deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9007", name: "Éowyn", number: Optional(7), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Spirit"), traits: Optional("Noble. Rohan."), keywords: nil, cost: Optional("9"), willpower: Optional("4"), attack: Optional("1"), defense: Optional("1"), health: Optional("3"), text: Optional("Action: Discard 1 card from your hand to give Eowyn +1 Ò until the end of the phase. This effect may be triggered by each player once each round.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9008", name: "Eleanor", number: Optional(8), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Spirit"), traits: Optional("Gondor. Noble."), keywords: nil, cost: Optional("7"), willpower: Optional("1"), attack: Optional("1"), defense: Optional("2"), health: Optional("3"), text: Optional("Response: Exhaust Eleanor to cancel the \"when revealed\" effects of a treachery card just revealed by the encounter deck. Then, discard that card, and replace it with the next card from the encounter deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9009", name: "Dunhere", number: Optional(9), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Spirit"), traits: Optional("Rohan. Warrior."), keywords: nil, cost: Optional("8"), willpower: Optional("1"), attack: Optional("2"), defense: Optional("1"), health: Optional("4"), text: Optional("Dunhere can target enemies in the staging area when he attacks alone. When doing so, he gets +1 Û.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9010", name: "Denethor", number: Optional(10), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Lore"), traits: Optional("Gondor. Noble. Steward."), keywords: nil, cost: Optional("8"), willpower: Optional("1"), attack: Optional("1"), defense: Optional("3"), health: Optional("3"), text: Optional("Action: Exhaust Denethor to look at the top card of the encounter deck. You may move that card to the bottom of the deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9011", name: "Glorfindel", number: Optional(11), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Lore"), traits: Optional("Noble. Noldor. Warrior."), keywords: nil, cost: Optional("12"), willpower: Optional("3"), attack: Optional("3"), defense: Optional("1"), health: Optional("5"), text: Optional("Action: Pay 1 resource from Glorfindel\'s pool to heal 1 damage on any character. (Limit once per round.)")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9012", name: "Beravor", number: Optional(12), quantity: Optional(1), unique: Optional("‰"), type: Optional("Hero"), sphere: Optional("Lore"), traits: Optional("Dunedain. Ranger."), keywords: nil, cost: Optional("10"), willpower: Optional("2"), attack: Optional("2"), defense: Optional("2"), health: Optional("4"), text: Optional("Action: Exhaust Beravor to choose a player. That player draws 2 cards. Limit once per round.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9013", name: "Guard of the Citadel", number: Optional(13), quantity: Optional(3), unique: nil, type: Optional("Ally"), sphere: Optional("Leadership"), traits: Optional("Gondor. Warrior."), keywords: nil, cost: Optional("2"), willpower: Optional("1"), attack: Optional("1"), defense: Optional("0"), health: Optional("2"), text: nil),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9014", name: "Faramir", number: Optional(14), quantity: Optional(2), unique: Optional("‰"), type: Optional("Ally"), sphere: Optional("Leadership"), traits: Optional("Gondor. Noble. Ranger."), keywords: nil, cost: Optional("4"), willpower: Optional("2"), attack: Optional("1"), defense: Optional("2"), health: Optional("3"), text: Optional("Action: Exhaust Faramir to choose a player. Each character controlled by that player gets +1 Ò until the end of the phase.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9015", name: "Son of Arnor", number: Optional(15), quantity: Optional(2), unique: nil, type: Optional("Ally"), sphere: Optional("Leadership"), traits: Optional("Dunedain."), keywords: nil, cost: Optional("3"), willpower: Optional("0"), attack: Optional("2"), defense: Optional("0"), health: Optional("2"), text: Optional("Response: After Son of Arnor enters play, choose an enemy card in the staging area or currently engaged with another player. Engage that enemy.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9016", name: "Snowbourn Scout", number: Optional(16), quantity: Optional(3), unique: nil, type: Optional("Ally"), sphere: Optional("Leadership"), traits: Optional("Rohan. Scout."), keywords: nil, cost: Optional("1"), willpower: Optional("0"), attack: Optional("0"), defense: Optional("1"), health: Optional("1"), text: Optional("Response: After Snowbourn Scout enters play, choose a location. Place 1 progress token on that location.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9017", name: "Silverlode Archer", number: Optional(17), quantity: Optional(2), unique: nil, type: Optional("Ally"), sphere: Optional("Leadership"), traits: Optional("Archer. Silvan."), keywords: Optional("Ranged."), cost: Optional("3"), willpower: Optional("1"), attack: Optional("2"), defense: Optional("0"), health: Optional("1"), text: nil),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9018", name: "Longbeard Orc Slayer", number: Optional(18), quantity: Optional(2), unique: nil, type: Optional("Ally"), sphere: Optional("Leadership"), traits: Optional("Dwarf. Warrior."), keywords: nil, cost: Optional("4"), willpower: Optional("0"), attack: Optional("2"), defense: Optional("1"), health: Optional("3"), text: Optional("Response: After Longbeard Orc Slayer enters play, deal 1 damage to each Orc enemy in play.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9019", name: "Brok Ironfist", number: Optional(19), quantity: Optional(1), unique: Optional("‰"), type: Optional("Ally"), sphere: Optional("Leadership"), traits: Optional("Dwarf. Warrior."), keywords: nil, cost: Optional("6"), willpower: Optional("2"), attack: Optional("2"), defense: Optional("1"), health: Optional("4"), text: Optional("Response: After a Dwarf hero you control leaves play, put Brok Ironfist into play from your hand.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9020", name: "Ever Vigilant", number: Optional(20), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Leadership"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose and ready 1 ally card.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9021", name: "Common Cause", number: Optional(21), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Leadership"), traits: nil, keywords: nil, cost: Optional("0"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Exhaust 1 hero you control to choose and ready a different hero.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9022", name: "For Gondor!", number: Optional(22), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Leadership"), traits: nil, keywords: nil, cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Until the end of the phase, all characters get +1 Û. All Gondor characters also get +1 Ú until the end of the phase.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9023", name: "Sneak Attack", number: Optional(23), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Leadership"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Put 1 ally card into play from your hand. At the end of the phase, if that ally is still in play, return it to your hand.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9024", name: "Valiant Sacrifice", number: Optional(24), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Leadership"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: After an ally card leaves play, that card\'s controller draws 2 cards.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9025", name: "Grim Resolve", number: Optional(25), quantity: Optional(1), unique: nil, type: Optional("Event"), sphere: Optional("Leadership"), traits: nil, keywords: nil, cost: Optional("5"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Ready all character cards in play.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9026", name: "Steward of Gondor", number: Optional(26), quantity: Optional(2), unique: Optional("‰"), type: Optional("Attachment"), sphere: Optional("Leadership"), traits: Optional("Gondor. Title."), keywords: Optional("Attach to a hero."), cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Attached hero gains the Gondor trait.\n\nAction: Exhaust Steward of Gondor to add 2 resources to attached hero\'s resource pool.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9027", name: "Celebrían\'s Stone", number: Optional(27), quantity: Optional(1), unique: Optional("‰"), type: Optional("Attachment"), sphere: Optional("Leadership"), traits: Optional("Artifact. Item."), keywords: Optional("Attach to a hero. Restricted."), cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Attached hero gains +2 Ò.\n\nIf attached hero is Aragorn, he also gains a Ê resource icon.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9028", name: "Veteran Axehand", number: Optional(28), quantity: Optional(3), unique: nil, type: Optional("Ally"), sphere: Optional("Tactics"), traits: Optional("Dwarf. Warrior."), keywords: nil, cost: Optional("2"), willpower: Optional("0"), attack: Optional("2"), defense: Optional("1"), health: Optional("2"), text: nil),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9029", name: "Gondorian Spearman", number: Optional(29), quantity: Optional(3), unique: nil, type: Optional("Ally"), sphere: Optional("Tactics"), traits: Optional("Gondor. Warrior."), keywords: Optional("Sentinel."), cost: Optional("2"), willpower: Optional("0"), attack: Optional("1"), defense: Optional("1"), health: Optional("1"), text: Optional("Response: After Gondorian Spearman is declared as a defender, deal 1 damage to the attacking enemy.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9030", name: "Horseback Archer", number: Optional(30), quantity: Optional(2), unique: nil, type: Optional("Ally"), sphere: Optional("Tactics"), traits: Optional("Rohan. Archer."), keywords: Optional("Ranged."), cost: Optional("3"), willpower: Optional("0"), attack: Optional("2"), defense: Optional("1"), health: Optional("2"), text: nil),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9031", name: "Beorn", number: Optional(31), quantity: Optional(1), unique: Optional("‰"), type: Optional("Ally"), sphere: Optional("Tactics"), traits: Optional("Beorning. Warrior."), keywords: nil, cost: Optional("6"), willpower: Optional("1"), attack: Optional("3"), defense: Optional("3"), health: Optional("6"), text: Optional("Action: Beorn gains +5 Û until the end of the phase. At the end of the phase in which you trigger this effect, shuffle Beorn back into your deck. (Limit once per round.)")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9032", name: "Blade Mastery", number: Optional(32), quantity: Optional(3), unique: nil, type: Optional("Event"), sphere: Optional("Tactics"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose a character. Until the end of the phase, that character gains +1 Û and +1 Ú.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9033", name: "Rain of Arrows", number: Optional(33), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Tactics"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Exhaust a character you control with the ranged keyword to choose a player. Deal 1 damage to each enemy engaged with that player.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9034", name: "Feint", number: Optional(34), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Tactics"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Combat Action: Choose an enemy engaged with a player. That enemy cannot attack that player this phase.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9035", name: "Quick Strike", number: Optional(35), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Tactics"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Exhaust a character you control to immediately declare it as an attacker (and resolve its attack) against any eligible enemy target.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9036", name: "Thicket of Spears", number: Optional(36), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Tactics"), traits: nil, keywords: nil, cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("You must use resources from 3 different heroes\' pools to pay for this card.\n\nAction: Choose a player. That player\'s engaged enemies cannot attack that player this phase.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9037", name: "Swift Strike", number: Optional(37), quantity: Optional(1), unique: nil, type: Optional("Event"), sphere: Optional("Tactics"), traits: nil, keywords: nil, cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: After a character is declared as a defender, deal 2 damage to the attacking enemy.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9038", name: "Stand Together", number: Optional(38), quantity: Optional(1), unique: nil, type: Optional("Event"), sphere: Optional("Tactics"), traits: nil, keywords: nil, cost: Optional("0"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose a player. That player may declare any number of his eligible characters as defenders against each enemy attacking him this phase.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9039", name: "Blade of Gondolin", number: Optional(39), quantity: Optional(2), unique: nil, type: Optional("Attachment"), sphere: Optional("Tactics"), traits: Optional("Item. Weapon."), keywords: Optional("Attach to a hero. Restricted."), cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Attached hero gets +1 Û when attacking an Orc .\n\nResponse: After attached hero attacks and destroys an enemy, place 1  progress token on the current quest.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9040", name: "Citadel Plate", number: Optional(40), quantity: Optional(2), unique: nil, type: Optional("Attachment"), sphere: Optional("Tactics"), traits: Optional("Item. Armor."), keywords: Optional("Attach to a hero. Restricted."), cost: Optional("4"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Attached hero gets +4 Hit Points.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9041", name: "Dwarven Axe", number: Optional(41), quantity: Optional(2), unique: nil, type: Optional("Attachment"), sphere: Optional("Tactics"), traits: Optional("Item. Weapon."), keywords: Optional("Attach to a hero. Restricted."), cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Attached hero gains +1 Û. (+2 Û instead if attached hero is a Dwarf.)")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9042", name: "Horn of Gondor", number: Optional(42), quantity: Optional(1), unique: Optional("‰"), type: Optional("Attachment"), sphere: Optional("Tactics"), traits: Optional("Item. Artifact."), keywords: Optional("Attach to a hero. Restricted."), cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: After a character leaves play, add 1 resource to attached hero\'s pool.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9043", name: "Wandering Took", number: Optional(43), quantity: Optional(2), unique: nil, type: Optional("Ally"), sphere: Optional("Spirit"), traits: Optional("Hobbit."), keywords: nil, cost: Optional("2"), willpower: Optional("1"), attack: Optional("1"), defense: Optional("1"), health: Optional("2"), text: Optional("Action: Reduce your threat by 3 to give control of Wandering Took to another player. Raise that player\'s threat by 3.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9044", name: "Lórien Guide", number: Optional(44), quantity: Optional(3), unique: nil, type: Optional("Ally"), sphere: Optional("Spirit"), traits: Optional("Silvan. Scout."), keywords: nil, cost: Optional("3"), willpower: Optional("1"), attack: Optional("1"), defense: Optional("0"), health: Optional("2"), text: Optional("Response: After Lórien Guide commits to a quest, place 1 progress token on the active location.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9045", name: "Northern Tracker", number: Optional(45), quantity: Optional(2), unique: nil, type: Optional("Ally"), sphere: Optional("Spirit"), traits: Optional("Dunedain. Ranger."), keywords: nil, cost: Optional("4"), willpower: Optional("1"), attack: Optional("2"), defense: Optional("2"), health: Optional("3"), text: Optional("Response: After Northern Tracker commits to a quest, place 1 progress token on each location in the staging area.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9046", name: "The Galadhrim\'s Greeting", number: Optional(46), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Reduce one player\'s threat by 6, or reduce each player\'s threat by 2.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9047", name: "Strength of Will", number: Optional(47), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("0"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: After you travel to a location, exhaust a Ê character to place 2 progress tokens on that location.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9048", name: "Hasty Stroke", number: Optional(48), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: Cancel a shadow effect just triggered during combat.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9049", name: "Will of the West", number: Optional(49), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose a player. Shuffle that player\'s discard pile back into his deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9050", name: "A Test of Will", number: Optional(50), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: Cancel the \"when revealed\" effects of a card that was just revealed from the encounter deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9051", name: "Stand and Fight", number: Optional(51), quantity: Optional(3), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("X"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose an ally with a printed cost of X in any player\'s discard pile. Put that ally into play under your control. (The chosen ally can belong to any sphere of influence.)")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9052", name: "A Light in the Dark", number: Optional(52), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose an enemy engaged with a player. Return that enemy to the staging area.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9053", name: "Dwarven Tomb", number: Optional(53), quantity: Optional(1), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Return 1 Ê card from your discard pile to your hand.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9054", name: "Fortune or Fate", number: Optional(54), quantity: Optional(1), unique: nil, type: Optional("Event"), sphere: Optional("Spirit"), traits: nil, keywords: nil, cost: Optional("5"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose a hero in any player\'s discard pile. Put that card into play, under its owner\'s control.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9055", name: "The Favor of the Lady", number: Optional(55), quantity: Optional(2), unique: nil, type: Optional("Attachment"), sphere: Optional("Spirit"), traits: Optional("Condition."), keywords: Optional("Attach to a hero."), cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Attached hero gains +1 Ò.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9056", name: "Power in the Earth", number: Optional(56), quantity: Optional(2), unique: nil, type: Optional("Attachment"), sphere: Optional("Spirit"), traits: Optional("Condition."), keywords: Optional("Attach to a location."), cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Attached location gets -1 $.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9057", name: "Unexpected Courage", number: Optional(57), quantity: Optional(1), unique: nil, type: Optional("Attachment"), sphere: Optional("Spirit"), traits: Optional("Condition."), keywords: Optional("Attach to a hero."), cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Exhaust Unexpected Courage to ready attached hero.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9058", name: "Daughter of the Nimrodel", number: Optional(58), quantity: Optional(3), unique: nil, type: Optional("Ally"), sphere: Optional("Lore"), traits: Optional("Silvan."), keywords: nil, cost: Optional("3"), willpower: Optional("1"), attack: Optional("0"), defense: Optional("0"), health: Optional("1"), text: Optional("Action: Exhaust Daughter of the Nimrodel to heal up to 2 damage on any 1 hero.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9059", name: "Erebor Hammersmith", number: Optional(59), quantity: Optional(2), unique: nil, type: Optional("Ally"), sphere: Optional("Lore"), traits: Optional("Dwarf. Craftsman."), keywords: nil, cost: Optional("2"), willpower: Optional("1"), attack: Optional("1"), defense: Optional("1"), health: Optional("3"), text: Optional("Response: After you play Erebor Hammersmith, return the topmost attachment in any player\'s discard pile to his hand.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9060", name: "Henamarth Riversong", number: Optional(60), quantity: Optional(1), unique: Optional("‰"), type: Optional("Ally"), sphere: Optional("Lore"), traits: Optional("Silvan."), keywords: nil, cost: Optional("1"), willpower: Optional("1"), attack: Optional("1"), defense: Optional("0"), health: Optional("1"), text: Optional("Action: Exhaust Henamarth Riversong to look at the top card of the encounter deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9061", name: "Miner of the Iron Hills", number: Optional(61), quantity: Optional(2), unique: nil, type: Optional("Ally"), sphere: Optional("Lore"), traits: Optional("Dwarf."), keywords: nil, cost: Optional("2"), willpower: Optional("0"), attack: Optional("1"), defense: Optional("1"), health: Optional("2"), text: Optional("Response: After Miner of the Iron Hills enters play, choose and discard 1 Condition attachment from play.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9062", name: "Gléowine", number: Optional(62), quantity: Optional(2), unique: Optional("‰"), type: Optional("Ally"), sphere: Optional("Lore"), traits: Optional("Minstrel. Rohan."), keywords: nil, cost: Optional("2"), willpower: Optional("1"), attack: Optional("0"), defense: Optional("0"), health: Optional("2"), text: Optional("Action: Exhaust Gléowine to choose a player. That player draws 1 card.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9063", name: "Lore of Imladris", number: Optional(63), quantity: Optional(3), unique: nil, type: Optional("Event"), sphere: Optional("Lore"), traits: nil, keywords: nil, cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose a character. Heal all damage from that character.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9064", name: "Lórien\'s Wealth", number: Optional(64), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Lore"), traits: nil, keywords: nil, cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose a player. That player draws 3 cards.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9065", name: "Radagast\'s Cunning", number: Optional(65), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Lore"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Quest Action: Choose an enemy in the staging area. Until the end of the phase, that enemy does not contribute its $.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9066", name: "Secret Paths", number: Optional(66), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Lore"), traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Quest Action: Choose a location in the staging area. Until the end of the phase, that location does not contribute its $.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9067", name: "Gandalf\'s Search", number: Optional(67), quantity: Optional(2), unique: nil, type: Optional("Event"), sphere: Optional("Lore"), traits: nil, keywords: nil, cost: Optional("X"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Look at the top X cards of any player\'s deck, add 1 of those cards to its owner\'s hand, and return the rest to the top of the deck in any order.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9068", name: "Beorn\'s Hospitality", number: Optional(68), quantity: Optional(1), unique: nil, type: Optional("Event"), sphere: Optional("Lore"), traits: nil, keywords: nil, cost: Optional("5"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Choose a player. Heal all damage on each hero controlled by that player.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9069", name: "Forest Snare", number: Optional(69), quantity: Optional(2), unique: nil, type: Optional("Attachment"), sphere: Optional("Lore"), traits: Optional("Item. Trap."), keywords: Optional("Attach to an enemy engaged with a player."), cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Attached enemy cannot attack.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9070", name: "Protector of Lórien", number: Optional(70), quantity: Optional(2), unique: nil, type: Optional("Attachment"), sphere: Optional("Lore"), traits: Optional("Title."), keywords: Optional("Attach to a hero."), cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Discard a card from your hand to give attached hero +1 Ú or +1 Ò until the end of the phase. Limit 3 times per phase.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9071", name: "Dark Knowledge", number: Optional(71), quantity: Optional(1), unique: nil, type: Optional("Attachment"), sphere: Optional("Lore"), traits: Optional("Condition."), keywords: Optional("Attach to a hero. Attached hero gets -1 Ò."), cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: Exhaust Dark Knowledge to look at 1 shadow card that was just dealt to an enemy attacking you.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9072", name: "Self Preservation", number: Optional(72), quantity: Optional(2), unique: nil, type: Optional("Attachment"), sphere: Optional("Lore"), traits: Optional("Skill."), keywords: Optional("Attach to a character."), cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Exhaust Self Preservation to heal 2 points of damage from attached character.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9073", name: "Gandalf", number: Optional(73), quantity: Optional(4), unique: Optional("‰"), type: Optional("Ally"), sphere: Optional("Neutral"), traits: Optional("Istari."), keywords: Optional("At the end of the round, discard Gandalf from play."), cost: Optional("5"), willpower: Optional("4"), attack: Optional("4"), defense: Optional("4"), health: Optional("4"), text: Optional("Response: After Gandalf enters play, (choose 1): draw 3 cards, deal 4 damage to 1 enemy in play, or reduce your threat by 5.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9074", name: "King Spider", number: Optional(74), quantity: Optional(2), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Creature. Spider."), keywords: nil, cost: nil, willpower: nil, attack: Optional("3"), defense: Optional("1"), health: Optional("3"), text: Optional("When Revealed: Each player must choose and exhaust 1 character he controls.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9075", name: "Hummerhorns", number: Optional(75), quantity: Optional(1), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Creature. Insect."), keywords: nil, cost: nil, willpower: nil, attack: Optional("2"), defense: Optional("0"), health: Optional("3"), text: Optional("Forced: After Hummerhorns engages you, deal 5 damage to a single hero you control.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9076", name: "Ungoliant\'s Spawn", number: Optional(76), quantity: Optional(1), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Creature. Spider."), keywords: nil, cost: nil, willpower: nil, attack: Optional("5"), defense: Optional("2"), health: Optional("9"), text: Optional("When Revealed: Each character currently committed to a quest gets -1 Ò until the end of the phase.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9077", name: "Great Forest Web", number: Optional(77), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Forest."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Travel: Each player must exhaust 1 hero he controls to travel here.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9078", name: "Mountains of Mirkwood", number: Optional(78), quantity: Optional(3), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Forest. Mountain."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Travel: Reveal the top card of the encounter deck and add it to the staging area to travel here.\n\nResponse: After Mountains of Mirkwood leaves play as an explored location, each player may search the top 5 cards of his deck for 1 card and add it to his hand. Shuffle the rest of the searched cards back into their owners\' decks.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9079", name: "Eyes of the Forest", number: Optional(79), quantity: Optional(1), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Each player discards all event cards in his hand.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9080", name: "Caught in a Web", number: Optional(80), quantity: Optional(2), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: The player with the highest threat level attaches this card to one of his heroes. (Counts as a Condition attachment with the text: \"Attached hero does not ready during the refresh phase unless you pay 2 resources from that hero\'s pool.\")")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9081", name: "Wolf Rider", number: Optional(81), quantity: Optional(1), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Goblin. Orc."), keywords: Optional("Surge."), cost: nil, willpower: nil, attack: Optional("2"), defense: Optional("0"), health: Optional("2"), text: nil),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9082", name: "Hill Troll", number: Optional(82), quantity: Optional(2), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Troll."), keywords: nil, cost: nil, willpower: nil, attack: Optional("6"), defense: Optional("3"), health: Optional("9"), text: Optional("Excess combat damage dealt by Hill Troll (damage that is dealt beyond the remaining hit points of the character damaged by its attack) must be assigned as an increase to your threat.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9083", name: "Goblin Sniper", number: Optional(83), quantity: Optional(2), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Goblin. Orc."), keywords: nil, cost: nil, willpower: nil, attack: Optional("2"), defense: Optional("0"), health: Optional("2"), text: Optional("During the encounter phase, players cannot optionally engage Goblin Sniper if there are other enemies in the staging area.\n\nForced: If Goblin Sniper is in the staging area at the end of the combat phase, each player deals 1 point of damage to 1 character he controls.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9084", name: "Marsh Adder", number: Optional(84), quantity: Optional(1), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Creature."), keywords: nil, cost: nil, willpower: nil, attack: Optional("4"), defense: Optional("1"), health: Optional("7"), text: Optional("Forced: Each time Marsh Adder attacks you, raise your threat by 1.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9085", name: "Wargs", number: Optional(85), quantity: Optional(2), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Creature."), keywords: nil, cost: nil, willpower: nil, attack: Optional("3"), defense: Optional("1"), health: Optional("3"), text: Optional("Forced: If Wargs is dealt a shadow card with no effect, return Wargs to the staging area after it attacks.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9086", name: "Despair", number: Optional(86), quantity: Optional(2), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Remove 4 progress tokens from the current quest card. (If there are fewer than 4 progress tokens on the quest, remove all progress tokens from that quest.)")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9087", name: "The Brown Lands", number: Optional(87), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Wasteland."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Forced: After the players travel to The Brown Lands, place 1 progress token on it.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9088", name: "The East Bight", number: Optional(88), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Wasteland."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When faced with the option to travel, the players must travel to The East Bight if there is no active location.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9089", name: "Dol Guldur Orcs", number: Optional(89), quantity: Optional(3), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Dol Guldur. Orc."), keywords: nil, cost: nil, willpower: nil, attack: Optional("2"), defense: Optional("0"), health: Optional("3"), text: Optional("When Revealed: The first player chooses 1 character currently committed to a quest. Deal 2 damage to that character.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9090", name: "Chieftan Ufthak", number: Optional(90), quantity: Optional(1), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Dol Guldur. Orc."), keywords: Optional("Chieftain Ufthak get +2Attack for each resource token on him."), cost: nil, willpower: nil, attack: Optional("3"), defense: Optional("3"), health: Optional("6"), text: Optional("Forced: After Chieftain Ufthak attacks, place 1 resource token on him.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9091", name: "Dol Guldur Beastmaster", number: Optional(91), quantity: Optional(2), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Dol Guldur. Orc."), keywords: nil, cost: nil, willpower: nil, attack: Optional("3"), defense: Optional("1"), health: Optional("5"), text: Optional("Forced: When Dol Guldur Beastmaster attacks, deal it 1 additional shadow card.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9092", name: "Driven by Shadow", number: Optional(92), quantity: Optional(1), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Each enemy and each location currently in the staging area gets +1 $ until the end of the phase. If there are no cards in the staging area, Driven by Shadow gains surge.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9093", name: "The Necromancer\'s Reach", number: Optional(93), quantity: Optional(3), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Deal 1 damage to each exhausted character.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9094", name: "Necromancer\'s Pass", number: Optional(94), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Stronghold. Dol Guldur."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Travel: The first player must discard 2 cards from his hand at random to travel here.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9095", name: "Enchanted Stream", number: Optional(95), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Forest."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("While Enchanted Stream is the active location, players cannot draw cards.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9096", name: "Forest Spider", number: Optional(96), quantity: Optional(4), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Creature. Spider."), keywords: nil, cost: nil, willpower: nil, attack: Optional("2"), defense: Optional("1"), health: Optional("4"), text: Optional("Forced: After Forest Spider engages a player, it gets +1 Û until the end of the round.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9097", name: "East Bight Patrol", number: Optional(97), quantity: Optional(1), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Goblin. Orc."), keywords: nil, cost: nil, willpower: nil, attack: Optional("3"), defense: Optional("1"), health: Optional("2"), text: nil),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9098", name: "Black Forest Bats", number: Optional(98), quantity: Optional(1), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Creature."), keywords: nil, cost: nil, willpower: nil, attack: Optional("1"), defense: Optional("0"), health: Optional("2"), text: Optional("When Revealed: Each player must choose 1 character currently committed to a quest, and remove that character from the quest. (The chosen character does not ready.)")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9099", name: "Old Forest Road", number: Optional(99), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Forest."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: After you travel to Old Forest Road, the first player may choose and ready 1 character he controls.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9100", name: "Forest Gate", number: Optional(100), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Forest."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: After you travel to Forest Gate, the first player may draw 2 cards.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9101", name: "Dungeon Jailor", number: Optional(101), quantity: Optional(2), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Dol Guldur. Orc."), keywords: nil, cost: nil, willpower: nil, attack: Optional("2"), defense: Optional("3"), health: Optional("5"), text: Optional("Forced: If Dungeon Jailor is in the staging area after the players have just quested unsuccessfully, shuffle 1 unclaimed objective card from the staging area back into the encounter deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9102", name: "Nazgûl of Dol Guldur", number: Optional(102), quantity: Optional(1), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Nazgul."), keywords: Optional("No attachments can be played on Nazgul of Dol Guldur."), cost: nil, willpower: nil, attack: Optional("4"), defense: Optional("3"), health: Optional("9"), text: Optional("Forced: When the prisoner is \"rescued\", move Nazgul of Dol Guldur into the staging area.\n\nForced: After a shadow effect dealt to Nazgul of Dol Guldur resolves, the engaged player must choose and discard 1 character he controls.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9103", name: "Cavern Guardian", number: Optional(103), quantity: Optional(2), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Undead."), keywords: Optional("Doomed 1."), cost: nil, willpower: nil, attack: Optional("2"), defense: Optional("1"), health: Optional("2"), text: nil),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9104", name: "Under the Shadow", number: Optional(104), quantity: Optional(2), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Until the end of the phase, raise the total $ in the  staging area by X, where X is the number of players in the game.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9105", name: "Iron Shackles", number: Optional(105), quantity: Optional(1), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Attach Iron Shackles to the top of the first player\'s deck. (Counts as a Condition attachment with the text: \"The next time a player would draw 1 or more cards from attached deck, discard Iron Shackles instead.\")")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9106", name: "Endless Caverns", number: Optional(106), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Dungeon."), keywords: Optional("Doomed 1. Surge."), cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: nil),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9107", name: "Tower Gate", number: Optional(107), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Dungeon."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Forced: After travelling to Tower Gate, each player places the top card of his deck, face down in front of him, as if it just engaged him from the staging area. These cards are called \"Orc Guard\", and act as enemies with: 1 hit point, 1 Û, and 1 Ú.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9108", name: "Gandalf\'s Map", number: Optional(108), quantity: Optional(1), unique: nil, type: Optional("Objective"), sphere: nil, traits: Optional("Item."), keywords: Optional("Guarded. Restricted."), cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Raise your threat by 2 to claim this objective when it is free of encounters. When claimed, attach Gandalf\'s Map to a hero you control. (Counts as an attachment. If detached, return Gandalf\'s Map to the staging area.) \n\nAttached hero cannot attack or defend.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9109", name: "Dungeon Torch", number: Optional(109), quantity: Optional(1), unique: nil, type: Optional("Objective"), sphere: nil, traits: Optional("Item."), keywords: Optional("Guarded. Restricted."), cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Raise your threat by 2 to claim this objective when it is free of encounters. When claimed, attach Dungeon Torch to a hero you control. (Counts as an attachment. If detached, return Dungeon Torch to the staging area.)\n\nForced: At the end of each round, raise attached hero\'s controller\'s threat by 2.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9110", name: "Shadow Key", number: Optional(110), quantity: Optional(1), unique: nil, type: Optional("Objective"), sphere: nil, traits: Optional("Item."), keywords: Optional("Guarded. Restricted."), cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Action: Raise your threat by 2 to claim this objective when it is free of encounters. When claimed, attach Shadow Key to a hero you control. (Counts as an attachment. If detached, return Shadow Key to the staging area.)\n\nForced: At the end of each round, attached hero suffers 1 damage.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9111", name: "Misty Mountain Goblins", number: Optional(111), quantity: Optional(3), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Goblin. Orc."), keywords: nil, cost: nil, willpower: nil, attack: Optional("2"), defense: Optional("1"), health: Optional("3"), text: Optional("Forced: After Misty Mountain Goblins attacks, remove 1 progress token from the current quest.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9112", name: "Massing at Night", number: Optional(112), quantity: Optional(1), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Reveal X additional cards from the encounter deck. X is the number of players in the game.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9113", name: "Banks of the Anduin", number: Optional(113), quantity: Optional(2), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Riverland."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Forced: If Banks of the Anduin leaves play, return it to the top of the encounter deck instead of placing it in the discard pile.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9114", name: "Gladden Fields", number: Optional(114), quantity: Optional(3), unique: nil, type: Optional("Location"), sphere: nil, traits: Optional("Marshland."), keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Forced: While Gladden Fields is the active location, each player must raise his threat by an additional point during the refresh phase.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9115", name: "Eastern Crows", number: Optional(115), quantity: Optional(3), unique: nil, type: Optional("Enemy"), sphere: nil, traits: Optional("Creature."), keywords: Optional("Surge."), cost: nil, willpower: nil, attack: Optional("1"), defense: Optional("0"), health: Optional("1"), text: Optional("Forced: After Eastern Crows is defeated, shuffle it back into the encounter deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9116", name: "Evil Storm", number: Optional(116), quantity: Optional(3), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Deal 1 damage to each character controlled by each player with a threat of 35 or higher.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9117", name: "Pursued by Shadow", number: Optional(117), quantity: Optional(2), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Each player raises his threat by 1 for each character he controls that is not currently committed to a quest.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9118", name: "Treacherous Fog", number: Optional(118), quantity: Optional(2), unique: nil, type: Optional("Treachery"), sphere: nil, traits: nil, keywords: nil, cost: nil, willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Each location in the staging area gets +1 $ until the end of the phase. Then, each player with a threat of 35 or higher chooses and discards 1 card from his hand.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9119", name: "Flies and Spiders", number: Optional(119), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Setup: Search the encounter deck for 1 copy of the Forest Spider and 1 copy of the Old Forest Road, and add them to the staging area. Then, shuffle the encounter deck.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9121", name: "A Fork in the Road", number: Optional(120), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Forced: When you defeat this stage, proceed to one of the 2 \"A Chosen Path\" stages, at random.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9123", name: "A Chosen Path", number: Optional(121), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Each player must search the encounter deck and discard pile for 1 Spider card of his choice, and add it to the staging area.\n\nThe players must find and defeat Ungoliant\'s Spawn to win this game.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9125", name: "A Chosen Path", number: Optional(122), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Players cannot defeat this stage while Ungoliant\'s Spawn is in play. If players defeat this stage, they have won the game.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9127", name: "The Necromancer\'s Tower", number: Optional(123), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Randomly select 1 hero card (among all the heroes controlled by the players) and turn it facedown. That hero is now considered a \"prisoner\", cannot be used, cannot be damaged, and does not collect resources, until it is \"rescued\" (as instructed by card effects) later in this quest.\n\nThe players, as a group, cannot play more than 1 ally card each round.\n\nPlayers cannot advance to the next stage of this quest unless they have at least 1 objective card.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9129", name: "Through the Caverns", number: Optional(124), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Response: After placing any number of progress tokens on this card, flip the \"prisoner\" hero card face-up, and place 1 damage token on it. This hero has been \"rescued\", and may now be used by its controller.\n\nThe players, as a group, cannot play more than 1 ally card each round.\n\nPlayers cannot advance to the next stage of this quest unless they have rescued the prisoner and have all 3 \"Escape from Dol Guldur\" objective cards.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9131", name: "Out of the Dungeons", number: Optional(125), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Forced: At the beginning of each quest phase, each player places the top card of his deck, face down in front of him, as if it just engaged him from the staging area. These cards are called \"Orc Guard\", and act as enemies with: 1 hit point, 1 Û, and 1 Ú.\n\nPlayers cannot defeat this stage while Nazgul of Dol Guldur is in play. If this stage is defeated and Nazgul of Dol Guldur is not in play, the players have won the game.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9133", name: "To the River...", number: Optional(126), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("1"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Search the encounter deck for 1 Hill Troll (if one is not already in play), and place it in the staging area. Shuffle the encounter deck.\n\nPlayers cannot defeat this stage while any Hill Troll cards are in play.")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9135", name: "Anduin Passage", number: Optional(127), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("2"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("Reveal 1 additional card from the encounter deck each quest phase. Do not make engagement checks during the encounter phase. (Each player may still optionally engage 1 enemy each encounter phase.)")),
      MemoryCard(id: "51223bd0-ffd1-11df-a976-0801200c9137", name: "Ambush on the Shore", number: Optional(128), quantity: Optional(1), unique: nil, type: Optional("Quest"), sphere: nil, traits: nil, keywords: nil, cost: Optional("3"), willpower: nil, attack: nil, defense: nil, health: nil, text: Optional("When Revealed: Reveal 2 encounter cards per player, and add them to the staging area.\n\nSkip the staging step of the quest phase for the remainder of the game.\n\nOnce there are no enemies in play, the players have won the game."))])
}
}
